name: Deploy to Digital Ocean
on:
  push:
    branches: [master, ci]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DigitalOcean
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_TOKEN }}
          password: ${{ secrets.DO_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ secrets.DO_REGISTRY }}/pw:latest
          build-args: |
            VITE_RESUME_LINK=${{ vars.RESUME_LINK }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update Containers
        uses: appleboy/ssh-action@v0.1.10
        env:
          TOKEN: ${{ secrets.DO_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            docker login registry.digitalocean.com
            docker-compose pull
            docker-compose up -d --remove-orphans
